"""empty message

Revision ID: 111c24b7f8d3
Revises: 
Create Date: 2019-11-22 17:30:03.095687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111c24b7f8d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
