"""empty message

Revision ID: 17be527c4b09
Revises: 111c24b7f8d3
Create Date: 2019-11-24 16:05:04.340659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17be527c4b09'
down_revision = '111c24b7f8d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'ticket_id')
    op.drop_column('event', 'rating_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('event', sa.Column('ticket_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
